### ISSUE TITLE
Extremely slow since d12 on a tiling winwowmanager

### ISSUE THREAD

**Issue by freshprince** [Baughn/Dwarf-Fortress--libgraphics-#7]
I'm using the tiling windowmanager [stumpwm](http://www.nongnu.org/stumpwm/).

Whenn running df from git-head it is very slow. I need 2 minutes to hilight "Quit" in the main menu.

The console gets flooded with this messages:

```
Asked for 102x30 grid
Setting to 1022x368, grid 102x30, zoom 1.000000
Using OpenGL output path with client-side arrays and off-screen framebuffer
Room for 12000 vertices allocated
Ideal catalog size: 314x300
```

When running df under twm it works smoothely. I guess there is a problem with my windowmanager trying to resize the df window all the time. This didn't happen when the df window had a fixed size.

**Comment by Baughn** [comment]
This is a bug in your window-manager; it needs to learn to respect window size hints. Xmonad doesn't have a problem. ;)

As it is, you should tell stumpwm to float the window.

**Comment by freshprince** [comment]
It works in a floating window. I'm gonna hassle the stumpwm devs. Thanks.

**Comment by Baughn** [comment]
I've fixed DF now. Bad interaction, probably not stumpwm bug as such; according to the xmonad devs, the way I was refusing some resizing events breaks the ICCCM.

**Comment by freshprince** [comment]
Is the fix already in HEAD because I still have this problem?

**Comment by Baughn** [comment]
It is not. Furthermore, I'm not sure I can complete this fix very soon; it causes regressions such as, oh, crashes in other fields.

For now, just configure stumpwm to float DF. Eventually I'll make it play well with tiling window managers, seeing as how I'm using one myself.

**Comment by freshprince** [comment]
Current HEAD works now in tiling mode. Thanks
